.git
.github
.husky
.jest
.vscode
scripts
standalone
test-reports

**/.next

# Ignore all services except web
# TODO: figure out how to make it work so web can still access types
# services/*
# !services/echo/src/services/** */ # Required to get response types
# !services/echo/src/types/** */ # Required to get response types
# !services/web

services/web/fly.toml
